### ISSUE TITLE
broccoli-uglify-js chokes on backtick from latest merge

### ISSUE THREAD

**Issue by noomerikal** [maestrooo/ember-cli-html5-validation#15]
Came across this after building with latest rev - 0.17. Rolling back to 0.16 works fine.  

Last update is the cause - https://github.com/maestrooo/ember-cli-html5-validation/commit/a25b5e6ea352da8c9d3c91aea0a7669b2df52e75#diff-b01c322b11fefa66b08bed71afb9e5fbR168

```
rm -rf dist tmp
ember build --environment=production

Unexpected character '`'
Error at new JS_Parse_Error (/tmp/build_24c9b6c226a8df7be52cd0e61d499141/node_modules/ember-cli-uglify/node_modules/broccoli-uglify-sourcemap/node_modules/uglify-js/lib/parse.js:196:18)
````

perhaps this would be fine:
```
element.after('<label class="input-error" role="alert" for="' + element.attr("id") + '">' + errorMessage + '</label>');
```

ember-cli: 0.2.7
ember-cli-uglify: 1.2.0

**Comment by bakura10** [comment]
ping @srsgores 

I think this is the string interpolation feature from ES6. Ember-Cli should handle that isn't it? I'm sorry, I'm not doing any ember work currently.

I think that we could still simplify this expression and stick to old string concatenation. The interpolation brings few benefits tbh.

**Comment by srsgores** [comment]
@noomerikal, not having any problems on my end.

``ember-cli-uglify 1.2.0`` as well.

Be sure to do ``npm install`` to make sure your deps are up to date.

**Comment by srsgores** [comment]
Ok, just bringing this back up, because I've encountered the same problem.  I am still unaware of why the backticks aren't working within addons, because they are ES6, but in any case, I will be pushing out the fix shortly.

Here are the details of the bug:

* Only occur when doing ``environment=production`` (does **not** occur when doing normal ``ember build``
* Results in a very ambiguous error message
* Occurs in both ``ember-cli#0.2.5`` and ``ember-cli#0.2.7``

It might be worth reporting this to the ember CLI team.  I need to investigate further.

**If you're eager to fix**:

Replace the one-liner:

```
element.after('<label class="input-error" role="alert" for="' + element.attr('id') + '">' + errorMessage + '</label>');
```

**Comment by srsgores** [comment]
Hmm, wondering now if this has something to do with the fact that addons are parsed in different *merge trees*.  Thus, addons may have to outwardly specify the ``ember-cli-babel`` dependency.

I'm still investigating.

**Comment by bakura10** [comment]
Thanks, that definitely looks like a bug on Ember-CLI side then.

**Comment by bakura10** [comment]
I've tag version 0.0.18 that reverts to old string concat mechanism. Thanks!
